name: Deploy frontend application
'on':
  push:
    branches:
      - test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}
      -
        name: prepare the docker-compose run
        run: |
              ls -l
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: biggib01/testing
      -
        name: prepare the docker-compose run
        run: |
               mkdir testing
               cp docker-compose.yml testing/docker-compose.yml
               cd testing
               docker-compose -f docker-compose.yml -H ${{ secrets.HOST_SERVER}} --skip-hostname-check down
               docker-compose -f docker-compose.yml -H ${{ secrets.HOST_SERVER}} --skip-hostname-check pull
               docker-compose -f docker-compose.yml -H ${{ secrets.HOST_SERVER}} --skip-hostname-check up -d
               